### ISSUE TITLE
.afk

### ISSUE THREAD

**Issue by alejandrogmvva2** [SpEcHiDe/UniBorg#38]
afk command does not work

**Comment by SpEcHiDe** [comment]
The plugin does not exist in my fork.

**Comment by cyberpz** [comment]
Inspiring command! 
Since i'm online but away from keyboard, i need a command that replies to people when I'm AFK for some moments at work, but it has to remember me to reply to all messages arrived in that fraction of time.
So, the bot saves all incoming messages, in "Private Messages", with a MessageID Link to directly go to the chat without looking for it, and removes the message when i actually replyed to the guy.

**Comment by SpEcHiDe** [comment]
The command is available in a previous version but not currently.
